server:
  port: 9003

spring:
  application:
    name: BOOKING-SERVICE

razorpay:
  key: rzp_test_hSr3FOlfuF8pZP
  secret: 8gaoQJOfRNwCXEaKYcf2jXVq

aes:
  key: "mysecretkey01234"
  iv: "myiv123456789010"

service:
  resort: http://localhost:9001
  email-service: http://localhost:9003/api/email/sendEmail;
  room: http://locahost:9002

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://15.206.125.179:8761/eureka/
#   instance:
#     hostname: 15.206.125.179
